spring.application.name=e-commerce-backend
spring.datasource.url=jdbc:mysql://localhost:3306/e_commerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.username=root

spring.datasource.password=Dinhtruong95
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

logging.level.org.springframework.security=DEBUG
# --- CLOUDINARY CONFIG ---
cloudinary.cloud-name=dwhm7rgtj
cloudinary.api-key=516129537579928
cloudinary.api-secret=6masWNLtdTA6e_kDF8VYWElvpAg

ghn.token=f1b34e03-c51a-11f0-a7eb-1a50c79059af
ghn.shopId=6123101
ghn.fromDistrictId=1442

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phamhaianhpc10@gmail.com
spring.mail.password=ttlokeclewemctkt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.debug=true
server.port=8080

app.mail.from=phamhaianhpc10@gmail.com
app.mail.fromName=E-Commerce Team

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB


